main:
  - name: Malware Analysis
    url: /malware/
    weight: 1
  - name: CTF Write-ups
    url: /writeups/
    weight: 2
#  - name: Cheat Sheets
#    url: /cheatsheets/
#    weight: 3
  - name: HacktheBox Write-ups
    url: /htb_writeups/
    weight: 4